USE [master]
GO

/****** Object:  Database [dbStarsUpPlanner]    Script Date: 22.01.2021 22:28:46 ******/
CREATE DATABASE [dbStarsUpPlanner]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbStarsUpPlanner', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\dbStarsUpPlanner.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbStarsUpPlanner_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\dbStarsUpPlanner_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dbStarsUpPlanner] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbStarsUpPlanner].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbStarsUpPlanner] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbStarsUpPlanner] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbStarsUpPlanner] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbStarsUpPlanner] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbStarsUpPlanner] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbStarsUpPlanner] SET  MULTI_USER 
GO

ALTER DATABASE [dbStarsUpPlanner] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbStarsUpPlanner] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbStarsUpPlanner] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbStarsUpPlanner] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbStarsUpPlanner] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbStarsUpPlanner] SET  READ_WRITE 
GO


